services:
  cypress: &cypress
    image: cypress/included:3.2.0
    working_dir: /e2e
    volumes:
      - .:/e2e
  cypress-open:
    <<: *cypress
    entrypoint:
      - cypress
    command: open --project .
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - .:/e2e
      - /tmp/.X11-unix:/tmp/.X11-unix
