version: "3.9"
# Profiles:
#   [default] Main app
#   ci: Continuous integration one-off tests
#   watch: Development watch mode

services:
  recipes: &recipes
    image: node:current-alpine
    working_dir: /yarba
    volumes:
      - ./yarba:/yarba
    ports:
      - 3000:3000
    entrypoint:
      - /usr/local/bin/npm
    command: ["run", "dev"]
    profiles:
      - watch
  start:
    <<: *recipes
    entrypoint: /bin/sh
    command:
      ["-c", "/usr/local/bin/npm run build ; /usr/local/bin/npm run start"]
    profiles:
      - prod

  cypress: &cypress
    image: cypress/included:3.2.0
    working_dir: /e2e
    volumes:
      - .:/e2e
    profiles:
      - ci
  cypress-open:
    <<: *cypress
    entrypoint: /usr/local/bin/cypress
    command: ["open", "--project", "."]
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - .:/e2e
      - /tmp/.X11-unix:/tmp/.X11-unix
    profiles:
      - watch
