version: "3.9"
# Profiles:
#   [default] Main app
#   ci: Continuous integration one-off tests
#   watch: Development watch mode

services:
  recipes: &recipes
    image: node:current-alpine
    working_dir: /yarba
    volumes:
      - ./yarba:/yarba
    ports:
      - 3000:3000
    entrypoint:
      - /usr/local/bin/npm
    command: ["run", "dev"]
    environment:
      - DB_URL=postgres://recipes:recipes@db:5432/recipes
    profiles:
      - watch
      - dev
  start:
    <<: *recipes
    entrypoint: /bin/sh
    command:
      ["-c", "/usr/local/bin/npm run build ; /usr/local/bin/npm run start"]
    ports: []
    profiles:
      - prod
      - ci
  watch:
    <<: *recipes
    command: ["run", "test:watch"]
    ports: []
    profiles:
      - watch
      - dev

  cypress: &cypress
    image: cypress/included:3.2.0
    working_dir: /e2e
    volumes:
      - .:/e2e
    profiles:
      - ci
  cypress-open:
    <<: *cypress
    entrypoint: /usr/local/bin/cypress
    command: ["open", "--project", "."]
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - .:/e2e
      - /tmp/.X11-unix:/tmp/.X11-unix
    profiles:
      - watch

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: recipes
      POSTGRES_PASSWORD: recipes
      POSTGRES_DB: recipes
    ports:
      - 5432:5432
    profiles:
      - watch
      - dev
      - db
      - ci
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    profiles:
      - db
